apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/himanshutak8/Learn_ArgoCD.git
    targetRevision: main
    path: module3/myapp-gitops/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-prod
  syncPolicy:
    # NO automated block — prod is manual sync (you click Sync / run argocd app sync)
    syncOptions:
      - CreateNamespace=true