apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/himanshutak8/Learn_ArgoCD.git
    targetRevision: main
    path: module3/myapp-gitops/overlays/dev          # ArgoCD runs `kustomize build` on this path
  destination:
    server: https://kubernetes.default.svc   # your Module 1 gotcha fix — the in-cluster name
    namespace: myapp-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true