apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp-prod
resources:
  - ../../base
namePrefix: prod-
patches:
  - path: replicas-patch.yaml
images:
  - name: nginx
    newTag: "1.27.0"     # prod starts pinned to the same "known-good" tag